
INSERT INTO `badge_type` VALUES (1,'ADREGSTANDARD','Standard',NULL,NULL,NULL,NULL),(2,'MINOR','Minor',NULL,NULL,NULL,NULL),(3,'ADREGSPONSOR','Sponsor',NULL,NULL,NULL,NULL),(4,'ADREGCOMMSPONSOR','Community Sponsor',NULL,NULL,NULL,NULL),(5,'GUEST','Guest',NULL,NULL,NULL,NULL),(6,'VENDOR','Vendor',NULL,NULL,NULL,NULL),(7,'STAFF','Staff',NULL,NULL,NULL,NULL),(8,'EXHIBITOR','Exhibitor',NULL,NULL,NULL,NULL);

INSERT INTO `badge_status` VALUES (1,'NEW','New',1,NULL,NULL,NULL,NULL),(2,'PICKEDUP','Picked Up',1,NULL,NULL,NULL,NULL),(3,'LOST','Lost',0,NULL,NULL,NULL,NULL),(4,'REVOKED','Revoked',0,NULL,NULL,NULL,NULL);

INSERT INTO `extra` VALUES ('SponsorBreakfast','Has purchased the Sunday sponsor breakfast.','2017-06-18 14:47:37','2017-06-18 14:47:37',1,1,1);

INSERT INTO `registration_status` VALUES (1,'New','Newly registered.',1,NULL,NULL,NULL,NULL),(2,'PickedUp','Badge picked up.',1,NULL,NULL,NULL,NULL),(3,'Revoked','Registation revoked.',0,NULL,NULL,NULL,NULL),(4,'Refunded','Registration refunded.',0,NULL,NULL,NULL,NULL),(5,'RolledOver','Registation rolled over.',0,NULL,NULL,NULL,NULL),(6,'Transferred','Registration transferred and is now invalid.',0,NULL,NULL,NULL,NULL),(7,'Duplicate - Active','This Registration is a suspected duplicate Registration',1,NULL,NULL,NULL,NULL),(8,'Duplicate - Inactive','This Registration is a suspected duplicate badge, however is now a non-active registration',0,NULL,NULL,NULL,NULL),(9,'Imported','Imported from Old Database',0,1,'2017-06-09 00:00:00',1,'2017-06-09 00:00:00');

INSERT INTO `registration_type` VALUES (1,'Online','Online Registration',NULL,NULL,NULL,NULL),(2,'Mail','Mail Registration',NULL,NULL,NULL,NULL),(3,'Group','Group Registration',NULL,NULL,NULL,NULL),(4,'Rollover','Rolled over the badge',NULL,NULL,NULL,NULL),(5,'Transfer','Registration received through transfer',NULL,NULL,NULL,NULL),(6,'Import','Imported through Old Database',1,'2017-06-09 00:00:00',1,'2017-06-09 00:00:00');

INSERT INTO `shirt` VALUES (1,'S','MensTee','MENS S',NULL,NULL,NULL,NULL),(2,'M','MensTee','MENS M',NULL,NULL,NULL,NULL),(3,'L','MensTee','MENS L',NULL,NULL,NULL,NULL),(4,'XL','MensTee','MENS XL',NULL,NULL,NULL,NULL),(5,'XLT','MensTee','MENS XL (Tall)',NULL,NULL,NULL,NULL),(6,'2XL','MensTee','MENS 2XL',NULL,NULL,NULL,NULL),(7,'2XLT','MensTee','MENS 2XL (Tall)',NULL,NULL,NULL,NULL),(8,'3XL','MensTee','MENS 3XL',NULL,NULL,NULL,NULL),(9,'3XLT','MensTee','MENS 3XL (Tall)',NULL,NULL,NULL,NULL),(10,'4XL','MensTee','MENS 4XL',NULL,NULL,NULL,NULL),(11,'S','WomensTee','WOMENS S',NULL,NULL,NULL,NULL),(12,'M','WomensTee','WOMENS M',NULL,NULL,NULL,NULL),(13,'L','WomensTee','WOMENS L',NULL,NULL,NULL,NULL),(14,'XL','WomensTee','WOMENS XL',NULL,NULL,NULL,NULL),(15,'2XL','WomensTee','WOMENS XXL',NULL,NULL,NULL,NULL);
